/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Date = IDL.Record({
  'day' : IDL.Int,
  'month' : IDL.Int,
  'year' : IDL.Int,
});
export const Time = IDL.Record({ 'hour' : IDL.Int, 'minute' : IDL.Int });
export const Reservation = IDL.Record({
  'date' : Date,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : Time,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'partySize' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], []),
  'submitReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Date, Time, IDL.Int, IDL.Text],
      [IDL.Int],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Date = IDL.Record({
    'day' : IDL.Int,
    'month' : IDL.Int,
    'year' : IDL.Int,
  });
  const Time = IDL.Record({ 'hour' : IDL.Int, 'minute' : IDL.Int });
  const Reservation = IDL.Record({
    'date' : Date,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : Time,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'partySize' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], []),
    'submitReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Date, Time, IDL.Int, IDL.Text],
        [IDL.Int],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };