/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Date { 'day' : bigint, 'month' : bigint, 'year' : bigint }
export interface Reservation {
  'date' : Date,
  'name' : string,
  'specialRequests' : string,
  'time' : Time,
  'email' : string,
  'timestamp' : bigint,
  'partySize' : bigint,
  'phone' : string,
}
export interface Time { 'hour' : bigint, 'minute' : bigint }
export interface _SERVICE {
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'submitReservation' : ActorMethod<
    [string, string, string, Date, Time, bigint, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];